# fly.toml app configuration file generated for lexa-agression-bot on 2025-09-08T11:00:05+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lexa-agression-bot'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[env]
  OPENAI_MODEL = 'gpt-4o-mini'

[[services]]
  internal_port = 8080
  protocol = 'tcp'
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [[services.ports]]
    port = 8080
    handlers = ['http']
  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/healthz'

[[services]]
  internal_port = 9000
  protocol = 'tcp'
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [[services.ports]]
    port = 9000
    handlers = ['http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
