[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E","F","I","UP","B"]
lint.ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]


